---
- name: Password expiration
  hosts: all
  become: true
  vars:
    myuser: "example"
  tasks:
    - name: Set password expiration
      ansible.builtin.user:
        name: "{{ myuser }}"
        password_expire_min: 7
        password_expire_max: 90
